version: '3.5'
services:
  ads:
    build: './'
    ports:
      - '3003:3003'
    networks:
      - ms_network
    deploy:
        resources:
            limits:
              cpus: 0.25
              memory: 500M

networks:
  ms_network:
    driver: bridge
    name: ms_network
